### ISSUE TITLE
Add CI config

### ISSUE THREAD

**Issue by msevestre** [esqLABS/OSPSuite.ParameterIdentification#6]
@PavelBal I am not sure if I'll be able to set it up under esqLABS.

**Comment by msevestre** [comment]
@PavelBal I cannot assign people to tasks

**Comment by PavelBal** [comment]
@msevestre I have invited you with Maintainer-access, that should be sufficient.

Let's discuss it maybe on Wed. Maybe we should directly start in the OSP-fork. No objections from our side, the only reason to start it here is because of the esqlabsR-dependency (we definitely will not make the whole package open source).

**Comment by msevestre** [comment]
@PavelBal Can the esqlabsR package be downloaded somehow? If not, this is somewhat useless no?

**Comment by msevestre** [comment]
Correct;-)
